### ISSUE TITLE
(Bug) Primary key

### ISSUE THREAD

**Issue by FelipeRos19** [GumpDev/worm#9]
Ao definir Primary Key gera um erro de "Syntax".
Versão utilizada: Worm 3.0.2-SNAPSHOT

Log do Console:
`[20:00:55 INFO]: [Worm Logger] [SQL] CREATE TABLE IF NOT EXISTS `PunishmentsActive`(`uuid` VARCHAR(36) NOT NULL, `type` INT(1) NOT NULL, `author` VARCHAR(16) NOT NULL, `reason` VARCHAR(16) NOT NULL, `evidence` VARCHAR(128) NOT NULL, `started_at` BIGINT NOT NULL, `finished_at` BIGINT NOT NULL, `id` INT(6) NOT NULL AUTO_INCREMENT, PRIMARY KEY())
[20:00:55 ERROR]: [Worm Logger] Something went wrong while creating table PunishmentsActive
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[patched_1.16.5.jar:git-Paper-794]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[patched_1.16.5.jar:git-Paper-794]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[patched_1.16.5.jar:git-Paper-794]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) ~[patched_1.16.5.jar:git-Paper-794]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) ~[patched_1.16.5.jar:git-Paper-794]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) ~[patched_1.16.5.jar:git-Paper-794]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
        at dev.gump.worm.WormQuery.executeUpdate(WormQuery.java:23) ~[?:?]
        at dev.gump.worm.Worm.lambda$init$0(Worm.java:48) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:00:55 INFO]: [Worm Logger] All worm tables were created!`

**Comment by Braayy** [comment]
Fixed with https://github.com/GumpDev/worm/commit/6ec44303c7c92fda18134e917e7f463144415d6d
